import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import api from '../services/api';

export default function Tickets() {
  const { bookingId } = useParams();
  const navigate = useNavigate();
  const [tickets, setTickets] = useState([]);

  useEffect(() => {
    api.get(`/tickets/${bookingId}`).then(res => setTickets(res.data.tickets)).catch(console.error);
  }, [bookingId]);

  const handleRefund = async () => {
      if(window.confirm("Cancel booking? This invokes the After_Booking_Cancellation Trigger!")) {
          try {
              await api.post('/refund', { bookingId });
              alert("Refund Processed! Seats returned via Triggers.");
              navigate('/');
          } catch(err) {
              alert("Refund failed");
          }
      }
  };

  return (
    <div className="max-w-2xl mx-auto">
      <div className="flex justify-between items-center mb-8">
        <h2 className="text-3xl font-bold flex items-center gap-2">🎫 Your Digital Tickets</h2>
        <button onClick={handleRefund} className="bg-red-500/10 text-red-400 border border-red-500/20 px-4 py-2 flex items-center gap-2 hover:bg-red-500 hover:text-white rounded-lg transition font-semibold">
           Cancel Booking
        </button>
      </div>

      <div className="grid gap-4">
        {tickets.map(t => (
          <div key={t.Ticket_Id} className="bg-gradient-to-r from-indigo-500/20 to-purple-500/20 border border-indigo-500/30 p-6 rounded-2xl flex justify-between items-center">
             <div>
                <p className="text-slate-400 text-sm mb-1">Ticket ID # {t.Ticket_Id}</p>
                <p className="text-2xl font-bold text-white mb-0">Seat: {t.Seat_Number}</p>
             </div>
             <div className="text-right">
                <span className="bg-green-500/20 text-green-400 px-3 py-1 rounded-full text-sm border border-green-500/20 inline-block mb-2">Confirmed directly by MySQL</span>
                <p className="text-slate-400 text-sm font-mono">BOOKING: REF-{t.Booking_Id}</p>
             </div>
          </div>
        ))}
        {tickets.length === 0 && <p className="text-center text-slate-400 py-10">Searching for tickets generated by Database Triggers...</p>}
      </div>
    </div>
  );
}
